---
title: "Shiny Apps"
author: ~
categories: ["R", "shiny"]
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

I just started learning how to make shiny apps. It's a fun way to demo data visualisations and statistical concepts.

* [plot demo](http://shiny.psy.gla.ac.uk/debruine/plotdemo/) Set the sample size, 
  main effects, and interaction effect for a 2x2 design, then view six different  
  visualisations of the simulated data.
* [varviz](http://shiny.psy.gla.ac.uk/debruine/varviz/): Simulate and visualise a 
  normal distribution with a specified number, mean and SD. (Present for Phil McAleer)
* [topcentile](http://shiny.psy.gla.ac.uk/debruine/topcentile/): Calculates 
  the ratio of group A and group B members above a specificed percentile. You 
  set the means and standard deviations for groups A and B (only normal 
  distributions for now).
* [coinsim](http://shiny.psy.gla.ac.uk/debruine/coinsim/): Flip a 
  virtual coin any number of times (with a bias that you set) and calculate the 
  exact binomial probability of getting the sequence with a fair coin.
* [normsim](http://shiny.psy.gla.ac.uk/debruine/normsim/): Simulate 
  a normal distribution of a specified number and mean (with SD = 1) and to run 
  a one-sample t-test against 0. You can visualise the distribution of each sample 
  and the distribution of p-values over all the samples you create.
