<!DOCTYPE html><html lang="en-us" >

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.3.0 for Hugo" />
  

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Lisa DeBruine" />

  
  
  
    
  
  <meta name="description" content="Shiny app for a face-rating example. library(tidyverse) library(lmerTest) set.seed(90210) Imagine you want to find out if Armenian women born on an even-numbered day are taller than women born on an odd-numbered day." />

  
  <link rel="alternate" hreflang="en-us" href="https://debruine.github.io/post/aggregating/" />

  









  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    <meta name="theme-color" content="#1565c0" />
  

  
  

  

  <link rel="stylesheet" href="/css/vendor-bundle.min.f1ecf783c14edc00c9320c205831ad8e.css" media="print" onload="this.media='all'">

  
  
  
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.2/css/academicons.min.css" integrity="sha512-KlJCpRsLf+KKu2VQa5vmRuClRFjxc5lXO03ixZt82HZUk41+1I0bD8KBSA0fY290ayMfWYI9udIqeOWSu1/uZg==" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    
    
    
    
      
      
    
    
    

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/github.min.css" crossorigin="anonymous" title="hl-light" media="print" onload="this.media='all'">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" media="print" onload="this.media='all'" disabled>
        
      
    

    
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.css" integrity="sha512-1xoFisiGdy9nvho8EgXuXvnpR5GAMSjFwp40gSRE3NwdUdIMIKuPa7bqoUhLD0O/5tPNhteAsE5XyyMi5reQVA==" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      
        
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
    
      
      <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap" media="print" onload="this.media='all'">
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.b1dff6f85aae5097c42eda0896577563.css" />

  




<script async src="https://www.googletagmanager.com/gtag/js?id=G-16Q0LBRCV4"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url, target) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           if (target !== '_blank') {
             document.location = url;
           }
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target, event.target.getAttribute('target'));  
  }

  gtag('js', new Date());
  gtag('config', 'G-16Q0LBRCV4', {});
  gtag('set', {'cookie_flags': 'SameSite=None;Secure'});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  

  

  




  
  
  

  

  
    <link rel="manifest" href="/manifest.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hud41de7153c7fa400a999f8d222dc5c78_8091_32x32_fill_lanczos_center_3.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hud41de7153c7fa400a999f8d222dc5c78_8091_180x180_fill_lanczos_center_3.png" />

  <link rel="canonical" href="https://debruine.github.io/post/aggregating/" />

  
  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary" />
  
    <meta property="twitter:site" content="@@lisadebruine" />
    <meta property="twitter:creator" content="@@lisadebruine" />
  
  <meta property="og:site_name" content="Lisa DeBruine" />
  <meta property="og:url" content="https://debruine.github.io/post/aggregating/" />
  <meta property="og:title" content="What&#39;s wrong with aggregating data? | Lisa DeBruine" />
  <meta property="og:description" content="Shiny app for a face-rating example. library(tidyverse) library(lmerTest) set.seed(90210) Imagine you want to find out if Armenian women born on an even-numbered day are taller than women born on an odd-numbered day." /><meta property="og:image" content="https://debruine.github.io/media/icon_hud41de7153c7fa400a999f8d222dc5c78_8091_512x512_fill_lanczos_center_3.png" />
    <meta property="twitter:image" content="https://debruine.github.io/media/icon_hud41de7153c7fa400a999f8d222dc5c78_8091_512x512_fill_lanczos_center_3.png" /><meta property="og:locale" content="en-us" />
  
    
      <meta
        property="article:published_time"
        content="2019-03-04T00:00:00&#43;00:00"
      />
    
    <meta property="article:modified_time" content="2019-03-04T00:00:00&#43;00:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://debruine.github.io/post/aggregating/"
  },
  "headline": "What's wrong with aggregating data?",
  
  "datePublished": "2019-03-04T00:00:00Z",
  "dateModified": "2019-03-04T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Lisa DeBruine"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Lisa DeBruine",
    "logo": {
      "@type": "ImageObject",
      "url": "https://debruine.github.io/media/icon_hud41de7153c7fa400a999f8d222dc5c78_8091_192x192_fill_lanczos_center_3.png"
    }
  },
  "description": "Shiny app for a face-rating example. library(tidyverse) library(lmerTest) set.seed(90210) Imagine you want to find out if Armenian women born on an even-numbered day are taller than women born on an odd-numbered day."
}
</script>

  

  

  

  

  <title>What&#39;s wrong with aggregating data? | Lisa DeBruine</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper   " data-wc-page-id="a12e8e65680c565baae5e358f183e933" >

  
  
  
  
  
  
  
  
  
  <script src="/js/wowchemy-init.min.8988fb2a4bba758785868cfcb5244555.js"></script>

  


<aside class="search-modal" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#" aria-label="Close"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control"
        aria-label="Search...">
        
      </div>

      
      

      

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>



  <div class="page-header">
    












<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Lisa DeBruine</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Lisa DeBruine</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      
        
          
          <li class="nav-item d-none d-lg-inline-flex">
            <a class="nav-link" href="/"  aria-label="">
              <i class="fas fa-" aria-hidden="true"></i>
            </a>
          </li>
        
      

      
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-label="Display preferences">
          <i class="fas fa-moon" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      
      

    </ul>

  </div>
</nav>


  </div>

  <div class="page-body">
    <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>What&#39;s wrong with aggregating data?</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    2019-03-04
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    7 min read
  </span>
  

  
  
  
  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/category/rstats/">rstats</a></span>
  

</div>

    





  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p class="info">
<a href="http://shiny.psy.gla.ac.uk/debruine/anova_vs_lmer/">Shiny app</a> for a face-rating example.
</p>
<pre class="r"><code>library(tidyverse)
library(lmerTest)
set.seed(90210)</code></pre>
<p>Imagine you want to find out if Armenian women born on an even-numbered day are taller than women born on an odd-numbered day. (I’ve chosen Armenian women because they’re the first row in <a href="https://doi.org/10.1371/journal.pone.0018962">this paper</a>.)</p>
<p>First, let’s simulate a group of 20 women born on even-numbered days and 20 women born on odd-numbered days.</p>
<pre class="r"><code>stim_n &lt;- 20
# height stats from https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0018962
height_m &lt;- 158.1
height_sd &lt;- 5.7

stim &lt;- tibble(
  stim_id = 1:(stim_n*2),
  birthday = rep(c(&quot;odd&quot;, &quot;even&quot;), stim_n),
  height = rnorm(stim_n*2, height_m, height_sd)
)</code></pre>
<p><img src="/post/aggregation_files/figure-html/unnamed-chunk-3-1.png" width="100%" /></p>
<p>Obviously, the oddness of date of birth is not going to have any effect on women’s actual height and a two-sample t-test confirms this. However, there is a small difference between the means of the groups just due to chance (2.81 cm).</p>
<pre class="r"><code>t.test(stim$height ~ stim$birthday)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  stim$height by stim$birthday
## t = -1.5, df = 38, p-value = 0.1
## alternative hypothesis: true difference in means between group even and group odd is not equal to 0
## 95 percent confidence interval:
##  -6.4997  0.8767
## sample estimates:
## mean in group even  mean in group odd 
##              154.9              157.7</code></pre>
<div id="measurement-with-error" class="section level3">
<h3>Measurement with Error</h3>
<p>But what if we don’t measure height from each women once, but have a few different raters estimate it? The raters will each have their own bias, systematically overestimating or underestimating height on average. Let’s simulate 20 raters who have biases with an SD of 2 cm.</p>
<pre class="r"><code>rater_n &lt;- 20
rater_bias_sd &lt;- 2

rater &lt;- tibble(
  rater_id = 1:rater_n,
  rater_bias = rnorm(rater_n, 0, rater_bias_sd)
)</code></pre>
<p><img src="/post/aggregation_files/figure-html/unnamed-chunk-6-1.png" width="100%" /></p>
<p>New we can get each rater to estimate the height of each woman. Their estimate is the woman’s actual height, plus the rater’s bias, plus some error (sampled from a normal distribution with a mean of 0 and an SD of 4 cm, since estimating height is hard).</p>
<pre class="r"><code>dat &lt;- expand.grid(
  rater_id = rater$rater_id,
  stim_id = stim$stim_id
) %&gt;%
  left_join(rater, by = &quot;rater_id&quot;) %&gt;%
  left_join(stim, by = &quot;stim_id&quot;) %&gt;%
  mutate(
    error = rnorm(nrow(.), 0, 4),
    estimate = height + rater_bias + error
  )</code></pre>
</div>
<div id="aggregating-by-stimuli" class="section level3">
<h3>Aggregating by Stimuli</h3>
<p>You can aggregate by stimuli, that is, average the 20 raters’ estimate for each stimulus. You now have 40 mean estimates that are fairly well-correlated with the women’s actual heights.</p>
<pre class="r"><code>dat_agg_by_stim &lt;- dat %&gt;%
  group_by(stim_id, birthday, height) %&gt;%
  summarise(mean_estimate = mean(estimate))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;stim_id&#39;, &#39;birthday&#39;. You can override using the `.groups` argument.</code></pre>
<p><img src="/post/aggregation_files/figure-html/unnamed-chunk-9-1.png" width="100%" /></p>
<p>You get pretty much the same result when you compare these mean estimates between the groups of women with odd and even birthdays.</p>
<pre class="r"><code>t.test(dat_agg_by_stim$mean_estimate ~ dat_agg_by_stim$birthday)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  dat_agg_by_stim$mean_estimate by dat_agg_by_stim$birthday
## t = -1.4, df = 38, p-value = 0.2
## alternative hypothesis: true difference in means between group even and group odd is not equal to 0
## 95 percent confidence interval:
##  -6.473  1.130
## sample estimates:
## mean in group even  mean in group odd 
##              155.2              157.9</code></pre>
</div>
<div id="aggregating-by-raters" class="section level3">
<h3>Aggregating by Raters</h3>
<p>Alternatively, you can aggregate by raters, that is, average the 20 odd-group estimates and 20 even-group estimates for each rater. Now raters are your unit of analysis, so you’ve increased your power by having 20 raters and a within-subject design (each rater estimates heights for both odd- and even-birthday groups).</p>
<pre class="r"><code>dat_agg_by_rater &lt;- dat %&gt;%
  group_by(rater_id, birthday) %&gt;%
  summarise(mean_estimate = mean(estimate)) %&gt;%
  spread(birthday, mean_estimate)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;rater_id&#39;. You can override using the `.groups` argument.</code></pre>
<pre class="r"><code>t.test(dat_agg_by_rater$odd, dat_agg_by_rater$even, paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  dat_agg_by_rater$odd and dat_agg_by_rater$even
## t = 11, df = 19, p-value = 0.000000002
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  2.145 3.198
## sample estimates:
## mean of the differences 
##                   2.672</code></pre>
<p>Now the difference between the odd- and even-birthday groups is highly significant! What’s going is that you now have a relatively accurate estimate of the chance mean difference between the 20 women in the odd-birthday group and the 20 women in the even-birthday group. Since raters are the unit of analysis, this effect is likely to generalise to the larger population of potential raters, but only when they are rating <strong>these exact stimuli</strong>. Your conclusions cannot generalise beyond the stimulus set used here.</p>
<p>While this seems like an obvious problem when the question is whether Armenian women with odd birthdays are taller or shorter than Armenian women with even birthdays, the problem is not so obvious for other questions, like whether boxers who won their last match have more masculine faces than boxers who lost their last match. The point of this tutorial isn’t to call out any particular studies (I’ve certainly done this wrong myself plenty of times in the past), but to illustrate the enormous problem with this method and to explain the solution.</p>
<p>The larger the number of raters, the larger this false positive problem becomes because you’re increasing power to detect the small chance diffference between the two groups. You can play around with how changing parameters changes the power and false positive rates for by-stimulus, by-rater, and mixed effect designs at <a href="http://shiny.psy.gla.ac.uk/debruine/anova_vs_lmer/">this shiny app</a>.</p>
</div>
<div id="mixed-effect-model" class="section level3">
<h3>Mixed Effect Model</h3>
<p>In the particular case above, we’re only interested in the between-stimulus (and within-rater) main effect of birthday oddness. Therefore, aggregating by stimuli doesn’t inflate your false positive rate, while aggregating by rater does. However, other designs might have increased false positives for aggregating by stimuli but not by rater, or when aggregating by either.</p>
<p>A mixed effects model avoids the problems of aggregation completely by modelling random variation for both the stimuli and raters, as well as random variation in the size of within-group effects.</p>
<p class="info">
I <a href="https://debruine.github.io/posts/coding-schemes/">effect code</a> the <code>birthday</code> variable to make interpretation of the effects easier).
</p>
<pre class="r"><code># effect-code birthday
dat$birthday.e &lt;- recode(dat$birthday, &quot;odd&quot; = 0.5, &quot;even&quot; = -0.5)

mod &lt;- lmer(estimate ~ birthday.e +
              # random slope for effect of birthday, random intercept for rater bias
              (1 + birthday.e || rater_id) + 
              # random intercept for variation in stim height
              (1 | stim_id), 
            data = dat)

summary(mod)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: estimate ~ birthday.e + (1 + birthday.e || rater_id) + (1 | stim_id)
##    Data: dat
## 
## REML criterion at convergence: 4687
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8414 -0.6590  0.0102  0.6776  2.6231 
## 
## Random effects:
##  Groups     Name        Variance      Std.Dev.
##  stim_id    (Intercept) 34.4640965341 5.870613
##  rater_id   birthday.e   0.0000000214 0.000146
##  rater_id.1 (Intercept) 10.0890113704 3.176320
##  Residual               15.8201186615 3.977451
## Number of obs: 800, groups:  stim_id, 40; rater_id, 20
## 
## Fixed effects:
##             Estimate Std. Error     df t value Pr(&gt;|t|)    
## (Intercept)   156.55       1.18  55.02  132.98   &lt;2e-16 ***
## birthday.e      2.67       1.88  38.00    1.42     0.16    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr)
## birthday.e 0.000 
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular</code></pre>
<p>The estimate for <code>(Intercept)</code> is just the mean height estimate (156.55 cm) and the estimate for <code>birthday.e</code> is the mean difference between the odd and even birthday groups (2.67 cm). You can now generalise the conclusions of this mixed effects model to both the population of raters and the population of stimuli.</p>
<p class="info">
Thanks to <a href="https://twitter.com/lpsatchell">Liam Satchell</a>, <a href="https://twitter.com/AlexJonesPhD">Alex Jones</a>, and <a href="https://twitter.com/Ben_C_J">Ben Jones</a> for the stimulating late-night Twitter discussion that prompted this blog post!
</p>
</div>
<div id="references" class="section level3">
<h3>References</h3>
<p>Plenty of papers have made this point much more thoroughly <span class="citation"><a href="#ref-Wolsiefer2017" role="doc-biblioref">Wolsiefer, Westfall, and Judd</a> (<a href="#ref-Wolsiefer2017" role="doc-biblioref">2017</a>)</span>.</p>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-KeepItMaximal" class="csl-entry">
Barr, Dale J, Roger Levy, Christoph Scheepers, and Harry J Tily. 2013. <span>“Random Effects Structure for Confirmatory Hypothesis Testing: Keep It Maximal.”</span> <em>Journal of Memory and Language</em> 68 (3): 10.1016/j.jml.2012.11.001.
</div>
<div id="ref-Coleman1964" class="csl-entry">
Coleman, E. B. 1964. <span>“Generalizing to a Language Population.”</span> <em>Psychological Reports</em> 14 (1): 219–26. <a href="https://doi.org/10.2466/pr0.1964.14.1.219">https://doi.org/10.2466/pr0.1964.14.1.219</a>.
</div>
<div id="ref-Judd2012" class="csl-entry">
Judd, Charles M., Jacob Westfall, and David A. Kenny. 2012. <span>“Treating Stimuli as a Random Factor in Social Psychology: A New and Comprehensive Solution to a Pervasive but Largely Ignored Problem.”</span> <em>Journal of Personality and Social Psychology</em> 103 (1): 54–69. <a href="https://doi.org/doi:10.1037/a0028347">https://doi.org/doi:10.1037/a0028347</a>.
</div>
<div id="ref-Wolsiefer2017" class="csl-entry">
Wolsiefer, Katie, Jacob Westfall, and Charles M. Judd. 2017. <span>“Modeling Stimulus Variation in Three Common Implicit Attitude Tasks.”</span> <em>Behavior Research Methods</em> 49 (4): 1193–1209. <a href="https://doi.org/10.3758/s13428-016-0779-0">https://doi.org/10.3758/s13428-016-0779-0</a>.
</div>
</div>
</div>

    </div>

    






<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/r/">R</a>
  
  <a class="badge badge-light" href="/tag/lmer/">lmer</a>
  
  <a class="badge badge-light" href="/tag/mixed-effects/">mixed effects</a>
  
  <a class="badge badge-light" href="/tag/anova/">anova</a>
  
  <a class="badge badge-light" href="/tag/aggregation/">aggregation</a>
  
  <a class="badge badge-light" href="/tag/simulation/">simulation</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=https://debruine.github.io/post/aggregating/&amp;text=What&amp;#39;s%20wrong%20with%20aggregating%20data?" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=https://debruine.github.io/post/aggregating/&amp;t=What&amp;#39;s%20wrong%20with%20aggregating%20data?" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=What&amp;#39;s%20wrong%20with%20aggregating%20data?&amp;body=https://debruine.github.io/post/aggregating/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=https://debruine.github.io/post/aggregating/&amp;title=What&amp;#39;s%20wrong%20with%20aggregating%20data?" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="whatsapp://send?text=What&amp;#39;s%20wrong%20with%20aggregating%20data?%20https://debruine.github.io/post/aggregating/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=https://debruine.github.io/post/aggregating/&amp;title=What&amp;#39;s%20wrong%20with%20aggregating%20data?" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>











  
  



  
  
  
    
  
  
  
  <div class="media author-card content-widget-hr">
    
      
      <a href="https://debruine.github.io/"><img class="avatar mr-3 avatar-circle" src="/author/lisa-debruine/avatar_huc377f31d86b0555d6e6ef77d249d1895_1222505_270x270_fill_q75_lanczos_center.jpg" alt="Lisa DeBruine"></a>
    

    <div class="media-body">
      <h5 class="card-title"><a href="https://debruine.github.io/">Lisa DeBruine</a></h5>
      <h6 class="card-subtitle">Professor of Psychology</h6>
      <p class="card-text">Lisa DeBruine is a professor of psychology at the University of Glasgow. Her substantive research is on the social perception of faces and kinship. Her meta-science interests include team science (especially the Psychological Science Accelerator), open documentation, data simulation, web-based tools for data collection and stimulus generation, and teaching computational reproducibility.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="/" >
        <i class="fas fa-"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/debruine" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://tech.lgbt/@debruine" target="_blank" rel="noopener">
        <i class="fab fa-mastodon"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.co.uk/citations?user=oLHcVYUAAAAJ" target="_blank" rel="noopener">
        <i class="fas fa-graduation-cap"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://osf.io/4i578/" target="_blank" rel="noopener">
        <i class="ai ai-osf"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://figshare.com/authors/Lisa_DeBruine/3235773" target="_blank" rel="noopener">
        <i class="ai ai-figshare"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="http://orcid.org/0000-0002-7523-5539" target="_blank" rel="noopener">
        <i class="ai ai-orcid"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
    <li>
      <a href="mailto:lisa.debruine@glasgow.ac.uk" >
        <i class="far fa-paper-plane"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>
















  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/post/coding-schemes/">Coding Schemes</a></li>
      
      <li><a href="/post/simulating-random-slopes/">Simulating Random Slopes</a></li>
      
      <li><a href="/post/simulating-mixed-effects/">Simulating Mixed Effects</a></li>
      
      <li><a href="/talk/mixed-effects-models-for-designs-with-randomly-sampled-stimuli/">Mixed effects models for designs with randomly sampled stimuli</a></li>
      
      <li><a href="/post/loops/">Loops</a></li>
      
    </ul>
  </div>
  





  </div>
</article>
  </div>

  <div class="page-footer">
    
    
    <div class="container">
      <footer class="site-footer">

  



  

  

  

  
  





  
  
  
  

  
  
  
    
  

  

  
  <p class="powered-by copyright-license-text">
    This work is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0" rel="noopener noreferrer" target="_blank">CC BY SA 4.0</a>
  </p>
  

  <p class="powered-by footer-license-icons">
    <a href="https://creativecommons.org/licenses/by-sa/4.0" rel="noopener noreferrer" target="_blank" aria-label="Creative Commons">
      <i class="fab fa-creative-commons fa-2x" aria-hidden="true"></i>
      <i class="fab fa-creative-commons-by fa-2x" aria-hidden="true"></i>
      
      
        <i class="fab fa-creative-commons-sa fa-2x" aria-hidden="true"></i>
      
    </a>
  </p>




  <p class="powered-by">
    
    
    
      
      
      
      
      
      
      Published with <a href="https://wowchemy.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Wowchemy</a> — the free, <a href="https://github.com/wowchemy/wowchemy-hugo-modules" target="_blank" rel="noopener">open source</a> website builder that empowers creators.
    
  </p>
</footer>

    </div>
    
  </div>

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

      

    
    <script src="/js/vendor-bundle.min.b73dfaac3b6499dc997741748a7c3fe2.js"></script>

    
    
    
      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/highlight.min.js" integrity="sha512-TDKKr+IvoqZnPzc3l35hdjpHD0m+b2EC2SrLEgKDRWpxf2rFCxemkgvJ5kfU48ip+Y+m2XVKyOCD85ybtlZDmw==" crossorigin="anonymous"></script>
        
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/r.min.js" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/python.min.js" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/latex.min.js" crossorigin="anonymous"></script>
        
      

    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.js" integrity="sha512-SeiQaaDh73yrb56sTW/RgVdi/mMqNeM2oBwubFHagc5BkixSpP1fvqF47mKzPGWYSSy4RwbBunrJBQ4Co8fRWA==" crossorigin="anonymous"></script>
    

    
    

    
    
    
      
      <script id="search-hit-fuse-template" type="text/x-template">
        <div class="search-hit" id="summary-{{key}}">
          <div class="search-hit-content">
            <div class="search-hit-name">
              <a href="{{relpermalink}}">{{title}}</a>
              <div class="article-metadata search-hit-type">{{type}}</div>
              <p class="search-hit-description">{{snippet}}</p>
            </div>
          </div>
        </div>
      </script>
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
      
    

    
    

    
    
    
    

    
    
      
      
      
      
      
      
      
    

    
    
    
    
    
    
    
    
      
      
    
    
    <script src="/en/js/wowchemy.min.d68ecd57c0ec1f1f61d65fd568f1c3a0.js"></script>

    
  <script async defer src="https://buttons.github.io/buttons.js"></script>




</body>
</html>
