---
title: "Lisa DeBruine"
---

Courses

* [The Research Cycle](research_cycle/)
* [Academic Webpages](acadweb/)

Shiny Apps

* [topcentile]( https://debruine.shinyapps.io/topcentile/)  

    This tool calculates the ratio of group A and group B members above a 
    specificed percentile. You set the means and standard deviations for groups 
    A and B (only normal distributions for now).
    
* [coinsim]( https://debruine.shinyapps.io/coinsim/)

    This tool lets you flip a virtual coin any number of times (with a bias that 
    you set) and calculate the exact binomial probability of getting the sequence 
    with a fair coin.

* [normsim]( https://debruine.shinyapps.io/normsim/)

    This tool lets you simulate a normal distribution of a specified number and 
    mean (with SD = 1) and to run a one-sample t-test against 0. You can visualise 
    the distribution of each sample and the distribution of p-values over all 
    the samples you create.


I also blog random things about R and Open Science.

* [psych::alpha()](psych_alpha.html)
* [rep()](rep.html)
* [scale()](scale.html)
* [coding schemes](coding.html)
* [pca](pca.html)
* [recode()](recode.html)
* [cumulative p](cumulative_p.html)
