{
  "hash": "80cdd9d8ca0c77ed26768f59d7ea053b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"What's wrong with aggregating data?\"\ndate: \"2019-03-04\"\nbibliography: [_bib.bib]\nslug: aggregating\ncategories: [\"R\", \"lmer\", \"mixed effects\", \"anova\", \"aggregation\", \"simulation\"]\n---\n\n\n\n\n\n<p class=\"info\">[Shiny app](http://shiny.psy.gla.ac.uk/debruine/anova_vs_lmer/) for a face-rating example.</p>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lmerTest)\nset.seed(90210)\n```\n:::\n\n\n\nImagine you want to find out if Armenian women born on an even-numbered day are taller than women born on an odd-numbered day. (I've chosen Armenian women because they're the first row in [this paper](https://doi.org/10.1371/journal.pone.0018962).) \n\nFirst, let's simulate a group of 20 women born on even-numbered days and 20 women born on odd-numbered days.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstim_n <- 20\n# height stats from https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0018962\nheight_m <- 158.1\nheight_sd <- 5.7\n\nstim <- tibble(\n  stim_id = 1:(stim_n*2),\n  birthday = rep(c(\"odd\", \"even\"), stim_n),\n  height = rnorm(stim_n*2, height_m, height_sd)\n)\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](aggregating_files/figure-html/unnamed-chunk-3-1.png){width=100%}\n:::\n:::\n\n\n\nObviously, the oddness of date of birth is not going to have any effect on women's actual height and a two-sample t-test confirms this. However, there is a small difference between the means of the groups just due to chance (2.81 cm).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(stim$height ~ stim$birthday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  stim$height by stim$birthday\nt = -1.5, df = 38, p-value = 0.1\nalternative hypothesis: true difference in means between group even and group odd is not equal to 0\n95 percent confidence interval:\n -6.4997  0.8767\nsample estimates:\nmean in group even  mean in group odd \n             154.9              157.7 \n```\n\n\n:::\n:::\n\n\n\n### Measurement with Error\n\nBut what if we don't measure height from each women once, but have a few different raters estimate it? The raters will each have their own bias, systematically overestimating or underestimating height on average. Let's simulate 20 raters who have biases with an SD of 2 cm. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrater_n <- 20\nrater_bias_sd <- 2\n\nrater <- tibble(\n  rater_id = 1:rater_n,\n  rater_bias = rnorm(rater_n, 0, rater_bias_sd)\n)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](aggregating_files/figure-html/unnamed-chunk-6-1.png){width=100%}\n:::\n:::\n\n\n\nNew we can get each rater to estimate the height of each woman. Their estimate is the woman's actual height, plus the rater's bias, plus some error (sampled from a normal distribution with a mean of 0 and an SD of 4 cm, since estimating height is hard).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- expand.grid(\n  rater_id = rater$rater_id,\n  stim_id = stim$stim_id\n) %>%\n  left_join(rater, by = \"rater_id\") %>%\n  left_join(stim, by = \"stim_id\") %>%\n  mutate(\n    error = rnorm(nrow(.), 0, 4),\n    estimate = height + rater_bias + error\n  )\n```\n:::\n\n\n\n### Aggregating by Stimuli\n\nYou can aggregate by stimuli, that is, average the 20 raters' estimate for each stimulus. You now have 40 mean estimates that are fairly well-correlated with the women's actual heights.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_agg_by_stim <- dat %>%\n  group_by(stim_id, birthday, height) %>%\n  summarise(mean_estimate = mean(estimate))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'stim_id', 'birthday'. You can override\nusing the `.groups` argument.\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](aggregating_files/figure-html/unnamed-chunk-9-1.png){width=100%}\n:::\n:::\n\n\n\nYou get pretty much the same result when you compare these mean estimates between the groups of women with odd and even birthdays.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(dat_agg_by_stim$mean_estimate ~ dat_agg_by_stim$birthday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  dat_agg_by_stim$mean_estimate by dat_agg_by_stim$birthday\nt = -1.4, df = 38, p-value = 0.2\nalternative hypothesis: true difference in means between group even and group odd is not equal to 0\n95 percent confidence interval:\n -6.473  1.130\nsample estimates:\nmean in group even  mean in group odd \n             155.2              157.9 \n```\n\n\n:::\n:::\n\n\n\n### Aggregating by Raters\n\nAlternatively, you can aggregate by raters, that is, average the 20 odd-group estimates and 20 even-group estimates for each rater. Now raters are your unit of analysis, so you've increased your power by having 20 raters and a within-subject design (each rater estimates heights for both odd- and even-birthday groups).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_agg_by_rater <- dat %>%\n  group_by(rater_id, birthday) %>%\n  summarise(mean_estimate = mean(estimate)) %>%\n  spread(birthday, mean_estimate)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'rater_id'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(dat_agg_by_rater$odd, dat_agg_by_rater$even, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  dat_agg_by_rater$odd and dat_agg_by_rater$even\nt = 11, df = 19, p-value = 0.000000002\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 2.145 3.198\nsample estimates:\nmean difference \n          2.672 \n```\n\n\n:::\n:::\n\n\n\nNow the difference between the odd- and even-birthday groups is highly significant! What's going is that you now have a relatively accurate estimate of the chance mean difference between the 20 women in the odd-birthday group and the 20 women in the even-birthday group. Since raters are the unit of analysis, this effect is likely to generalise to the larger population of potential raters, but only when they are rating **these exact stimuli**. Your conclusions cannot generalise beyond the stimulus set used here.\n\nWhile this seems like an obvious problem when the question is whether Armenian women with odd birthdays are taller or shorter than Armenian women with even birthdays, the problem is not so obvious for other questions, like whether boxers who won their last match have more masculine faces than boxers who lost their last match. The point of this tutorial isn't to call out any particular studies (I've certainly done this wrong myself plenty of times in the past), but to illustrate the enormous problem with this method and to explain the solution.\n\nThe larger the number of raters, the larger this false positive problem becomes because you're increasing power to detect the small chance diffference between the two groups. You can play around with how changing parameters changes the power and false positive rates for by-stimulus, by-rater, and mixed effect designs at [this shiny app](http://shiny.psy.gla.ac.uk/debruine/anova_vs_lmer/).\n\n\n### Mixed Effect Model\n\nIn the particular case above, we're only interested in the between-stimulus (and within-rater) main effect of birthday oddness. Therefore, aggregating by stimuli doesn't inflate your false positive rate, while aggregating by rater does. However, other designs might have increased false positives for aggregating by stimuli but not by rater, or when aggregating by either.\n\nA mixed effects model avoids the problems of aggregation completely by modelling random variation for both the stimuli and raters, as well as random variation in the size of within-group effects. \n\n<p class=\"info\">I [effect code](https://debruine.github.io/posts/coding-schemes/) the `birthday` variable to make interpretation of the effects easier).</p>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# effect-code birthday\ndat$birthday.e <- recode(dat$birthday, \"odd\" = 0.5, \"even\" = -0.5)\n\nmod <- lmer(estimate ~ birthday.e +\n              # random slope for effect of birthday, random intercept for rater bias\n              (1 + birthday.e || rater_id) + \n              # random intercept for variation in stim height\n              (1 | stim_id), \n            data = dat)\n\nsummary(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: estimate ~ birthday.e + (1 + birthday.e || rater_id) + (1 | stim_id)\n   Data: dat\n\nREML criterion at convergence: 4687\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.8414 -0.6590  0.0102  0.6776  2.6231 \n\nRandom effects:\n Groups     Name        Variance      Std.Dev.\n stim_id    (Intercept) 34.4640965331 5.870613\n rater_id   birthday.e   0.0000000214 0.000146\n rater_id.1 (Intercept) 10.0890113688 3.176320\n Residual               15.8201186615 3.977451\nNumber of obs: 800, groups:  stim_id, 40; rater_id, 20\n\nFixed effects:\n            Estimate Std. Error     df t value Pr(>|t|)    \n(Intercept)   156.55       1.18  55.02  132.98   <2e-16 ***\nbirthday.e      2.67       1.88  38.00    1.42     0.16    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr)\nbirthday.e 0.000 \noptimizer (nloptwrap) convergence code: 0 (OK)\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n:::\n\n\n\n\nThe estimate for `(Intercept)` is just the mean height estimate (156.55 cm) and the estimate for `birthday.e` is the mean difference between the odd and even birthday groups (2.67 cm). You can now generalise the conclusions of this mixed effects model to both the population of raters and the population of stimuli.\n\n<p class=\"info\">Thanks to [Liam Satchell](https://twitter.com/lpsatchell), [Alex Jones](https://twitter.com/AlexJonesPhD), and [Ben Jones](https://twitter.com/Ben_C_J) for the stimulating late-night Twitter discussion that prompted this blog post!</p>\n\n### References\n\nPlenty of papers have made this point much more thoroughly [@KeepItMaximal, @Coleman1964, @Judd2012, @Wolsiefer2017]. \n\n\n",
    "supporting": [
      "aggregating_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}