{
  "hash": "c738c7f17920a80169e67e9dd194ca28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Coding Schemes\"\ndate: \"2017-06-23\"\nslug: coding-schemes\ncategories: [\"R\", \"coding\", \"effect\", \"treatment\", \"lmer\", \"mixed effects\", \"simulation\"]\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lmerTest)\n```\n:::\n\n\nHow you choose to code categorical variables changes how you can interpret the intercept and effects of those variables. My favourite [tutorial on coding schemes](http://talklab.psy.gla.ac.uk/tvw/catpred/) explains things in detail. I'm just adding some concrete examples below.\n\nFirst, I simulated a data frame of 100 raters rating 100 faces each. Female faces get ratings with a mean of 6; male faces get ratings with a mean of 5 (I know, ratings are usually ordinal integers, but let's pretend we used something like a slider). To simulate random effects, both raters and faces have random intercepts with SDs of 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(555)  # for reproducibility; delete when running simulations\n\nn_raters <- 100\nn_faces <- 100\n\nfemale_mean <- 6\nmale_mean <- 5\n\nraters <- tibble(\n  rater_id = 1:n_raters,\n  rater_i = rnorm(n_raters)\n)\n\nfaces <- tibble(\n  face_id = 1:n_faces,\n  face_i = rnorm(n_faces),\n  face_sex = rep(c(\"female\", \"male\"), each = n_faces/2)\n)\n\ndf <- expand.grid(\n  face_id = faces$face_id,\n  rater_id = raters$rater_id\n) %>%\n  left_join(faces, by = \"face_id\") %>%\n  left_join(raters, by = \"rater_id\") %>%\n  mutate(\n    face_sex_i = ifelse(face_sex==\"male\", male_mean, female_mean),\n    error = rnorm(nrow(.)),\n    rating = face_i + rater_i + face_sex_i + error\n  )\n```\n:::\n\n\nCalculate the means and SDs of the female and male faces.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|face_sex |  mean|    SD|\n|:--------|-----:|-----:|\n|female   | 5.940| 1.767|\n|male     | 5.114| 1.649|\n\n\n:::\n:::\n\n\n\nAlways graph your data to confirm you simulated it correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  ggplot(aes(face_sex, rating)) + \n  geom_violin() +\n  geom_boxplot(width=0.2)\n```\n\n::: {.cell-output-display}\n![](coding-schemes_files/figure-html/coding-orig-data-1.png){width=672}\n:::\n:::\n\n\nRecode face sex using treatment, sum, or effect coding.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf2 <- df %>%\n  mutate(\n    face_sex.tr = recode(face_sex, \"female\" = 1, \"male\" = 0),\n    face_sex.sum = recode(face_sex, \"female\" = -1, \"male\" = 1),\n    face_sex.e = recode(face_sex, \"female\" = -0.5, \"male\" = 0.5)\n  )\n```\n:::\n\n\nNow we analyse the data using each of the 4 styles of coding. I'm just going to show the table of fixed effects.\n\n## Categorical coding\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lmerTest::lmer(rating ~ face_sex + \n                       (1 | face_id) + \n                       (1 + face_sex | rater_id), \n                     data = df2)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|             | Estimate| Std. Error|      df| t value| Pr(>&#124;t&#124;)|\n|:------------|--------:|----------:|-------:|-------:|------------------:|\n|(Intercept)  |    5.940|      0.174| 173.383|  34.081|                  0|\n|face_sexmale |   -0.826|      0.203|  98.600|  -4.069|                  0|\n\n\n:::\n:::\n\n\nNote that the intercept coefficient is equal to the female mean (5.94) and the effect of face sex is how much less the male mean is (5.114 - 5.94 = -0.826).\n\n## Treatment coding\n\n::: {.cell}\n\n```{.r .cell-code}\nm.tr <- lmerTest::lmer(rating ~ face_sex.tr + \n               (1 | face_id) + \n               (1 + face_sex.tr | rater_id), \n             data = df2)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|            | Estimate| Std. Error|      df| t value| Pr(>&#124;t&#124;)|\n|:-----------|--------:|----------:|-------:|-------:|------------------:|\n|(Intercept) |    5.114|      0.172| 169.515|  29.720|                  0|\n|face_sex.tr |    0.826|      0.203|  98.611|   4.069|                  0|\n\n\n:::\n:::\n\n\nTreatment coding is the same as categorical coding, but gives you more control over what the reference category is. Here, the reference category is `male` and the \"treatment\" category is `female`, so the intercept coefficient is equal to the male mean (5.114) and the effect of face sex is how much more the female mean is (5.94 - 5.114 = 0.826).\n\n## Sum coding\n\n::: {.cell}\n\n```{.r .cell-code}\nm.sum <- lmerTest::lmer(rating ~ face_sex.sum + \n                (1 | face_id) + \n                (1 + face_sex.sum | rater_id), \n              data = df2)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|             | Estimate| Std. Error|      df| t value| Pr(>&#124;t&#124;)|\n|:------------|--------:|----------:|-------:|-------:|------------------:|\n|(Intercept)  |    5.527|      0.140| 194.675|  39.387|                  0|\n|face_sex.sum |   -0.413|      0.102|  98.601|  -4.069|                  0|\n\n\n:::\n:::\n\n\nWith sum coding, the intercept coefficient is equal to the overall mean ignoring face sex (i.e.,  (5.94 + 5.114)/2 = 5.527) and the effect of face sex is how much above and below that each of the two face sexes differ from the mean (i.e., (5.94 - 5.114)/2 =  0.413).\n\n## Effect coding\n\n::: {.cell}\n\n```{.r .cell-code}\nm.e <- lmerTest::lmer(rating ~ face_sex.e + \n              (1 | face_id) + \n              (1 + face_sex.e | rater_id), \n            data = df2)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|            | Estimate| Std. Error|      df| t value| Pr(>&#124;t&#124;)|\n|:-----------|--------:|----------:|-------:|-------:|------------------:|\n|(Intercept) |    5.527|      0.140| 194.683|  39.387|                  0|\n|face_sex.e  |   -0.826|      0.203|  98.604|  -4.069|                  0|\n\n\n:::\n:::\n\n\nWith effect coding, the intercept coefficient is the same as sum coding and the effect of face sex is how much the two face sexes differ from each other (i.e., 5.94 - 5.114 =  0.826). Note that this coefficient is double that from the sum coding.\n",
    "supporting": [
      "coding-schemes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}